#!/bin/bash

echo "What is the amount borrowed?"
read P
echo "What is the annual interest rate?"
read rate
echo "How many years is the loan?"
read n
N=$( echo " $n * 12 "| bc -l)
R=$( echo " (( $rate / 100 ) / 12) "|bc -l)
M=$( echo " (( $R * $P ) / (1 - (( 1 + $R )) ^ ( -$N ))) "|bc -l)
MF=$( echo " scale=2; $M / 1 "|bc -l)
echo "The monthly payment you should expect for this mortgage is \$$MF"
